config/routes.rb
AppSearches::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :apps, only: [:show, :index]
  
  root to: 'pages#home'
  
  match '/seller/:artist_id', to: 'apps#index'
  match '/top/apps', to: 'apps#index', as: :top_apps
  match '/top/apps/:type', to: 'apps#index', as: :top_apps_type
  match '/:type/apps', to: 'apps#index', as: :newest_apps

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'

end

app/models/app.rb
class App < ActiveRecord::Base
  # for searching
  include PgSearch
  pg_search_scope :search,
                  :against => [[:track_name, 'A'], [:seller_name, 'A'], [:genres, 'B'], [:description, 'D'], [:release_notes, 'D']],
                  :using => {:tsearch => {:prefix => true, :normalization => 2}}
  
  attr_accessible :kind, :features, :supported_devices, :is_gamecenter_enabled, :artist_view_url, :artwork_url_60, 
                  :screenshot_urls, :ipad_screenshot_urls, :artwork_url_512, :artist_id, :artist_name, :price, 
                  :version, :description, :genre_ids, :release_date, :seller_name, :currency, :genres, :bundle_id, :track_id,
                  :track_name, :primary_genre_name, :genre_id, :release_notes, :wrapper_type, :content_advisory_rating, 
                  :artwork_url_100, :track_censored_name, :track_view_url, :language_codes, :file_size_bytes, :formatted_price,
                  :average_user_rating_for_current_version, :user_rating_count_for_current_version, :track_content_rating, 
                  :average_user_rating, :user_rating_count, :rank, :rank_history
  
  serialize :features, Array
  serialize :supported_devices, Array
  serialize :screenshot_urls, Array
  serialize :ipad_screenshot_urls, Array
  serialize :genre_ids, Array
  serialize :genres, Array
  serialize :language_codes, Array
  serialize :rank_history, Hash
  
  # for paginating
  self.per_page = 30
  
  scope :free, where(formatted_price: "Free")
  scope :paid, where("formatted_price != 'Free'")
  scope :top, where("rank IS NOT NULL")
  scope :price, lambda { |price| { :conditions => ['price = ?', price] } }
  
  def free?
    formatted_price.downcase == "free"
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  
  def index
    @time = Date.today - 1.day
    if params[:type].try(:downcase) == "free"
      @apps = App.top.free.order(:rank).paginate(page: params[:page], per_page: App.per_page)
    elsif params[:type].try(:downcase) == "paid"
      @apps = App.top.paid.order(:rank).paginate(page: params[:page], per_page: App.per_page)
    elsif params[:type].try(:downcase) == "newest"
      @apps = App.order("release_date DESC").paginate(page: params[:page], per_page: App.per_page)
    elsif params[:search]
      @apps = App.search(params[:search]).paginate(page: params[:page], per_page: App.per_page)
      if @apps.empty?
        render 'apps/no_search_results'
      end
    elsif params[:fuzzy_search]
      
    elsif params[:price]
      @apps = App.price(params[:price].to_f).order(:rank).paginate(page: params[:page], per_page: App.per_page)      
    elsif params[:artist_id]
      @seller_name = App.find_by_artist_id(params[:artist_id]).seller_name
      @apps = App.where(artist_id: params[:artist_id].to_i).paginate(page: params[:page], per_page: App.per_page)
      render 'apps/seller'
    else
      @apps = App.paginate(page: params[:page], per_page: App.per_page)
    end
  end
  
  def show
    @app = App.find(params[:id])
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @user = User.new
    if signed_in?
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or root_url
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Thanks! We'll contact you when we've got something exciting to show you!"
    else
      flash[:error] = @user.errors.full_messages.to_sentence.humanize
    end
    redirect_to root_url
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to root_url
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def add_linkshare(url)
    site_id = "2976862"
    return url + "&partnerId=30&siteID=#{site_id}"
  end

  def full_title(page_title)
    base_title = "App Searches - find the best iPhone and iPad apps"
    if page_title.empty?
      base_title
    else
      page_title
    end
  end
  
  def image_url(source)
    "#{root_url[0...-1]}#{image_path(source)}"
  end

  def humanize_index(index, page, per_page)
    if page == 0
      return index + 1
    else
      return index + 1 + per_page * (page-1)
    end
  end

end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/apps/_index.html.erb
<div id="top-apps">
  <ul class="thumbnails">
  <% @apps.each_with_index do |app, index| %>
  <div class="app-card">
    <li class="span2">
      <%= link_to image_tag(app.artwork_url_100, size: "100x100", class: "artwork-100"), app, class: "thumbnail radius-100" %>
      <% if params[:type].present? && (params[:type] == "free" || params[:type] == "paid") %>
      <% if !app.rank_history[@time].nil? && app.rank.to_i < app.rank_history[@time].to_i %>
          <i class="icon-chevron-up"></i>
        <% elsif !app.rank_history[@time].nil? && app.rank.to_i > app.rank_history[@time].to_i %>
          <i class="icon-chevron-down"></i>
        <% else %>
          <i class="icon-minus"></i>
        <% end %>
      <% end %>
      <%= link_to app.track_name, app %><br>
      <%= link_to 'By: ' + app.seller_name.to_s, '/seller/' + app.artist_id.to_s %><br>
  
      <% if app.free? %>
        <span class="label label-success"><%= app.formatted_price %></span>
      <% else %>
        <span class="label label-inverse"><%= app.formatted_price%></span>
      <% end %>
    </li>
  </div>
  <% end %>
  </ul>
  
  <div class="pagination pagination-small pagination-centered">
    <%= will_paginate(@apps) %>
  </div>

</div>

app/views/apps/_tabs.html.erb
<ul class="nav nav-tabs">
  <% if params[:type] == "newest" %>
    <li class="active"><%= link_to 'Newest Apps', newest_apps_path("newest") %></li>
  <% else %>
    <li><%= link_to 'Newest Apps', newest_apps_path("newest") %></li>
  <% end %>
  
  <% if params[:type] == "free" %>
    <li class="active"><%= link_to 'Top Free Apps', top_apps_type_path('free') %></li>
  <% else %>
    <li><%= link_to 'Top Free Apps', top_apps_type_path('free') %></li>
  <% end %>
  
  <% if params[:type] == "paid" %>
    <li class="active"><%= link_to 'Top Paid Apps', top_apps_type_path('paid') %></li>
  <% else %>
    <li><%= link_to 'Top Paid Apps', top_apps_type_path('paid') %></li>
  <% end %>
  
  <% if params[:price] == "0.99" %>
    <li class="active"><%= link_to 'Top Apps for $0.99', top_apps_path(price: 0.99) %></li>
  <% else %>
    <li><%= link_to 'Top Apps for $0.99', top_apps_path(price: 0.99) %></li>
  <% end %>
  
</ul>

app/views/apps/index.html.erb
<%= render 'layouts/header' %>
<%= render 'apps/tabs' %>
<%= render 'apps/index' %>

app/views/apps/no_search_results.html.erb
<%= render 'layouts/header' %>
<%= render 'apps/tabs' %>

<div class="no-search-results">
  <%= "Oh no, there are no search results for your query '#{params[:search]}'." %>
</div>

app/views/apps/seller.html.erb
<%= render 'layouts/header' %>
<%= render 'apps/tabs' %>

<div class="seller-name">
  <%= "All apps by #{@seller_name}" %>
</div>

<%= render 'apps/index' %>

app/views/apps/show.html.erb
<%= render 'layouts/header' %>
<%= render 'apps/tabs' %>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span4">
      <div class="app-name">
        <%= @app.track_name %>
      </div>
      <div class="app-seller">
        By: <%= link_to @app.seller_name, '/seller/' + @app.artist_id.to_s %>
      </div>
      <div class="app-image">
        <%= image_tag @app.artwork_url_100, class: "artwork-100", size: "200x200" %>
      </div>
      <div class="app-release-date">
        <%= @app.release_date.to_date %>
      </div>
      <div class="app-link-itunes">
        <%= link_to "View on iTunes website", add_linkshare(@app.track_view_url) %>
      </div>
    </div>
  
    <div class="span8">
      <div class="app-description">
        <%= simple_format h @app.description %>
      </div>
      <div class="app-whats-new">
        What's new in version <%= @app.version %>
        <%= simple_format h @app.release_notes %>
      </div>
    </div>
  </div>
  
  <div class="row-fluid">
    <div class="span12">
      <div class="app-screenshots">
        <% @app.screenshot_urls.each do |screen| %>
          <%= image_tag screen, class: "iphone-screen" %>
        <% end %>
      </div>
    </div>
  </div>
  
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
</footer>

app/views/layouts/_google_analytics.html.erb
<script type='text/javascript'>
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36897260-1']);
  _gaq.push(['_setDomainName', 'appsearch.es']);
  _gaq.push(['_setAllowLinker', true]);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/layouts/_header.html.erb
<header class="header">
  <span class="app-logo">
    <%= link_to "APPSEARCH.ES", root_path %>
  </span>
  <span class="header-search">
    <form action="<%= apps_path %>" method="get" >
      <div class="input-append">
        <%= text_field_tag :search, params[:search], value: params[:search] %>  
        <%= submit_tag "Search", name: nil, class: "btn" %>
      </div>
    </form>
  </span>
  <span class="total-apps">
    <%= "#{number_with_delimiter(App.count, :delimiter => ',')} apps have been indexed." %>
  </span>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.5, minimum-scale=0.5">
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= render 'layouts/google_analytics' %>
    <meta property="og:image" content='<%= image_url "iphone.png" %>'>
  </head>
  <body>    
    <div class="main">
      <div class="content">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "alert alert-#{key}") %>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div id="preregister">
  <div id="prereg-text">
    <h1>APPSEARCH.ES</h1>
    <h3>Search for the apps that you want.</h3>
    <h3><%= link_to "Top Free Apps", top_apps_type_path('free') %></h3>
    <h3><%= link_to "Top Paid Apps", top_apps_type_path('paid') %></h3>
    <h3><%= link_to "Newest Apps", newest_apps_path("newest") %></h3>
    
    <form action="<%= apps_path %>" method="get" >
      <div class="input-append">
        <%= text_field_tag :search, params[:search], autofocus: "autofocus" %>  
        <%= submit_tag "Search", name: nil, class: "btn" %>
      </div>
    </form>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<h1>Update your profile</h1>
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirm Password" %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<h1>All users</h1>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="signup">
  <h1>Sign up</h1>
  <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Password Confirmation" %>
    <%= f.password_field :password_confirmation %>
    <br>
    <%= f.submit "Create my account", class: "btn flat-button" %>
    
    <p>Already have an account? <%= link_to "Sign in here!", signin_path %></p>
  <% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>